student:
  arch: vit_small
  patch_size: 14
  block_chunks: 4
train:
  dataset_path: ImageNet:split=TRAIN
  batch_size_per_gpu: 128
crops:
  local_crops_size: 98
optim:
  epochs: 200
multiscale:
  loss_weight: 1.0
  separate_head: true
  head_n_prototypes: 2048
  debug_wandb: on
ibot:
  loss_weight: 1.0